### ISSUE TITLE
[추가 문제] 9_5 - 탐욕법(Greedy) 체육복

### ISSUE THREAD

**Issue by tiaz0128** [AltongStudy/Algorithm#126]
https://programmers.co.kr/learn/courses/30/lessons/42862

**Comment by wj2kim** [comment]
function solution(n, lost, reserve) {  
    const filteredLost = lost.filter((a) => !reserve.includes(a));
  
    let filteredReserve = reserve.filter((r) => !lost.includes(r));
  
    return n - filteredLost.filter((a) => {
        const left = filteredReserve.find((r) => Math.abs(r - a) <= 1);         
        if (!left) return true;
        filteredReserve = filteredReserve.filter((r) => r !== left);
    }).length;
}

solution(5, [2, 4], [1, 3, 5]);

**Comment by ro-ssang** [comment]
```javascript
function solution(n, lost, reserve) {
    const prevStudents = Array(n + 1).fill(1);
    const nextStudents = Array(n + 1).fill(1);
    lost.forEach(num => {
        prevStudents[num] = 0;
        nextStudents[num] = 0;
    });
    reserve.forEach(num => {
        if (lost.indexOf(num) < 0) {
            prevStudents[num - 1] = 1;
            nextStudents[num + 1] = 1;
        } else {
            prevStudents[num] = 1;
            nextStudents[num] = 1;
        }
    });
    return Math.max(
        prevStudents.slice(1, n + 1).reduce((a, b) => a + b),
        nextStudents.slice(1, n + 1).reduce((a, b) => a + b)
    );
}
```
