### ISSUE TITLE
[추가 문제] 8_3 - Strong Password

### ISSUE THREAD

**Issue by tiaz0128** [AltongStudy/Algorithm#71]
## 문제 링크
https://www.hackerrank.com/challenges/strong-password/problem

## 문제 설명
- 패스위드의 길이는 최소 6글자 이상이다. Its length is at least 6.
- 최소 하나의 이상의 숫자를 사용한다. It contains at least one digit.
- 최소 하나의 이상의 소문자를 사용한다. It contains at least one lowercase English character.
- 최소 하나의 이상의 대문자를 사용한다. It contains at least one uppercase English character.
- 최소 하나의 이상의 특수문자를 사용한다. It contains at least one special character. The special characters are: `!@#$%^&*()-+`

## 입력 / 출력
- `n` : 패스워드의 길이 , `password` : 검사 할 패스워드 문자열
- 입력받은 패스위드에서 위의 경우에 부합하는 패스워드로 만들기 위해서 **필요한 추가 문자의 갯수**를 리턴하라.

```js
function minimumNumber(n, password) {

  // 알고리즘 작성

}
```

**Comment by goawmfhfl** [comment]
![스크린샷 2021-08-19 20 37 45](https://user-images.githubusercontent.com/79143800/130062133-151a521e-d7cb-4cf5-9335-36b96b5763de.png)

**Comment by tiaz0128** [comment]
```js
function minimumNumber(n, password) {
    // Return the minimum number of characters to make the password strong
    const numbers = /[0-9]/g
    const lower_case = /[a-z]/g
    const upper_case = /[A-Z]/g
    const special_characters = /[!@#$%^&*()\-+]/g
    
    let cnt = 0;
    
    if(!numbers.test(password)) cnt++;
    if(!lower_case.test(password)) cnt++;
    if(!upper_case.test(password)) cnt++;
    if(!special_characters.test(password)) cnt++;
    if(n + cnt < 6) cnt += 6 - (n + cnt)
    
    return cnt;
}
```

**Comment by ro-ssang** [comment]
`function isIncluded(regex, password) {
  return password.match(regex)?.length > 0;
}

function minimumNumber(n, password) {
  const numberRegex = new RegExp(/[0-9]/);
  const lowercaseRegex = new RegExp(/[a-z]/);
  const capitalRegex = new RegExp(/[A-Z]/);
  const specialRegex = new RegExp(/[!@#$%^&*()-+]/);

  let count = 0;
  if (isIncluded(numberRegex, password)) {
    count += 1;
  }
  if (isIncluded(lowercaseRegex, password)) {
    count += 1;
  }
  if (isIncluded(capitalRegex, password)) {
    count += 1;
  }
  if (isIncluded(specialRegex, password)) {
    count += 1;
  }
  return n - count;
}

console.log(minimumNumber(5, '2bbbb'));
`

**Comment by wj2kim** [comment]
function minimumNumber(n, pass) {
  const maxLength = n;
  let maxNumber = 1;
  let maxLower = 1;
  let maxUpper = 1;
  let maxSpecial = 1;
  let need = 0;
  
  for(let i = 0; i < pass.length; i++) {
    if (pass[i].match(/[0-9]/g)) {
      maxNumber = 0;
    } else if (pass[i].match(/[a-z]/g)) {
      maxLower = 0
    } else if (pass[i].match(/[A-Z]/g)) {
      maxUpper = 0
    } else (pass[i].match(/[!@#$%^&*]/g)){
      maxSpecial = 0;
    }
  }
  
  if ( pass.length < maxLength) {
    need = maxLength - pass.length
  }
  
  return need += maxNumber += maxLower += maxUpper += maxSpecial;
}
