### ISSUE TITLE
[추가 문제] 8_4 - K번째수

### ISSUE THREAD

**Issue by tiaz0128** [AltongStudy/Algorithm#82]
https://programmers.co.kr/learn/courses/30/lessons/42748

**Comment by wj2kim** [comment]
function solution(clothes) {
    var answer = 0;
    
    let obj = {};
    
    clothes.forEach((cloth, idx) => {
         obj[cloth[1]] ? obj[cloth[1]] += 1 : obj[cloth[1]] = 1;
    });
  
    console.log("obj", obj);

    return answer;
}

const answer = [["yellowhat", "headgear"], ["bluesunglasses", "eyewear"], ["green_turban", "headgear"]];

solution(answer);

**Comment by wj2kim** [comment]
function solution(clothes) {
    var answer = 0;
    
    let obj = {};
    
    clothes.forEach((cloth, idx) => {
         obj[cloth[1]] ? obj[cloth[1]] += 1 : obj[cloth[1]] = 1;
    });
  
    console.log("obj", obj);

    return answer;
}
